<a href="https://colab.research.google.com/github/katsukiyamamoto/EU_M_Math/blob/main/Chap05_Ex_01_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#5-1-2

import numpy as np
import numpy.random as random
import scipy as sp

import matplotlib.pyplot as plt
import matplotlib as mpl
%matplotlib inline

%precision 3

'%.3f'

In [4]:
#5-2-1

sample_array = np.arange(10)
print('sample_array:',sample_array)


print(sample_array)

sample_array_slice = sample_array[0:5]
print(sample_array_slice)

sample_array_slice[0:3] = 10
print(sample_array_slice)

print(sample_array)

sample_array: [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[10 10 10  3  4]
[10 10 10  3  4  5  6  7  8  9]


In [5]:
#5-2-1-1

sample_array_copy = np.copy(sample_array)
print(sample_array_copy)

sample_array_copy[0:3] = 20

print(sample_array)

[10 10 10  3  4  5  6  7  8  9]
[10 10 10  3  4  5  6  7  8  9]


In [6]:
#5-2-1-2

sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data=random.randn(5,5)

print(sample_names)
print(data)


sample_names == 'a'
data[sample_names == ['a']]

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [7]:
#5-2-1-3

cond_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])

print((np.where(cond_data, x_array, y_array)))

[  1   2 300 400   5]


In [8]:
#練習問題5-1

sample_names = np.array(['a', 'b', 'c', 'd', 'a'])
random.seed(0)
data=random.randn(5,5)

print(sample_names)
print(data)

sample_names == 'b'
data[sample_names == ['b']]

['a' 'b' 'c' 'd' 'a']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [12]:
#練習問題5-２

data[sample_names != ['c']]

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [13]:
#練習問題5-3

cond_data = np.array([True,True,False,False,True])

x_array = np.array([1,2,3,4,5])
y_array = np.array([6,7,8,9,10])

print((np.where(cond_data, y_array, x_array)))

[ 6  7  3  4 10]


In [14]:
#5-2-2-1

cond_data = np.array([True,True,False,False,True])

print(cond_data)

print(np.unique(cond_data))

[ True  True False False  True]
[False  True]


In [15]:
#5-2-2-2

sample_data = np.arange(10)
print('元データ:', sample_data)
print('全ての要素の平方根:', np.sqrt(sample_data))
print('全ての要素のネイピア指数関数:', np.exp(sample_data))

元データ: [0 1 2 3 4 5 6 7 8 9]
全ての要素の平方根: [0.    1.    1.414 1.732 2.    2.236 2.449 2.646 2.828 3.   ]
全ての要素のネイピア指数関数: [1.000e+00 2.718e+00 7.389e+00 2.009e+01 5.460e+01 1.484e+02 4.034e+02
 1.097e+03 2.981e+03 8.103e+03]


In [16]:
#5-2-2-3
sample_multi_array_data1 = np.arange(9).reshape(3,3)

print(sample_multi_array_data1)

print('最小値:', sample_multi_array_data1.min())
print('最大値:', sample_multi_array_data1.max())
print('平均:', sample_multi_array_data1.mean())
print('合計:', sample_multi_array_data1.sum())

print('行の合計:', sample_multi_array_data1.sum(axis=0))
print('列の合計:', sample_multi_array_data1.sum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
最小値: 0
最大値: 8
平均: 4.0
合計: 36
行の合計: [ 9 12 15]
列の合計: [ 3 12 21]


In [18]:
#5-2-2-4

cond_data = np.array([True,True,False,False,True])
print('Trueが少なくとも１つあるかどうか:', cond_data.any())
print('全てTrueかどうか:', cond_data.all())

sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)
print('５よりも大きい数字がいくつあるか:', (sample_multi_array_data1>5).sum())

Trueが少なくとも１つあるかどうか: True
全てTrueかどうか: False
[[0 1 2]
 [3 4 5]
 [6 7 8]]
５よりも大きい数字がいくつあるか: 3


In [19]:
#5-2-2-5

sample_multi_array_data1 = np.arange(9).reshape(3,3)
print(sample_multi_array_data1)

print('対角成分:', np.diag(sample_multi_array_data1))
print('対角成分の和:', np.trace(sample_multi_array_data1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
対角成分: [0 4 8]
対角成分の和: 12


In [20]:
#練習問題5-4

sample_multi_array_data2 = np.arange(16).reshape(4,4)
print(sample_multi_array_data2)
print('全ての要素の平方根:', np.sqrt(sample_multi_array_data2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
全ての要素の平方根: [[0.    1.    1.414 1.732]
 [2.    2.236 2.449 2.646]
 [2.828 3.    3.162 3.317]
 [3.464 3.606 3.742 3.873]]


In [21]:
#練習問題5-5

print('最小値:', sample_multi_array_data2.min())
print('最大値:', sample_multi_array_data2.max())
print('平均:', sample_multi_array_data2.mean())
print('合計:', sample_multi_array_data2.sum())

最小値: 0
最大値: 15
平均: 7.5
合計: 120


In [22]:
#練習問題5-6

print('対角成分の和:', np.trace(sample_multi_array_data2))

対角成分の和: 30


In [25]:
#5-2-3-1

sample_array = np.arange(10)
print(sample_array)

sample_array2 = sample_array.reshape(2,5)
print(sample_array2)

sample_array2.reshape(5,2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
#5-2-3-2

sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

print(sample_array3)
print(sample_array4)

np.concatenate([sample_array3,sample_array4],axis=0)

np.vstack([sample_array3,sample_array4])

np.concatenate([sample_array3,sample_array4],axis=1)

np.hstack([sample_array3,sample_array4])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [27]:
#5-2-3-3

sample_array3 = np.array([[1,2,3],[4,5,6]])
sample_array4 = np.array([[7,8,9],[10,11,12]])

sample_array_vstack = np.vstack([sample_array3,sample_array4])

print(sample_array_vstack)

first,second,third = np.split(sample_array_vstack,[1,3])

print(first)
print(second)
print(third)

sample_array5 = np.array([[13,14,15],[16,17,18],[19,20,21]])
sample_array_vstack2 = np.vstack([sample_array3,sample_array4,sample_array5])

print(sample_array_vstack2)

first,second,third,fourth = np.split(sample_array_vstack2,[2,3,5])

print('1つ目:\n', first, '\n')
print('2つ目:\n', second, '\n')
print('3つ目:\n', third, '\n')
print('4つ目:\n', fourth, '\n')

print(first[0])
print(first[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[1 2 3]]
[[4 5 6]
 [7 8 9]]
[[10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
1つ目:
 [[1 2 3]
 [4 5 6]] 

2つ目:
 [[7 8 9]] 

3つ目:
 [[10 11 12]
 [13 14 15]] 

4つ目:
 [[16 17 18]
 [19 20 21]] 

[1 2 3]
[4 5 6]


In [28]:
#5-2-3-4

first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 6, 6, 6, 6, 6])

In [29]:
#5-2-3-5

sample_array = np.arange(10)
print(sample_array)

sample_array + 3

[0 1 2 3 4 5 6 7 8 9]


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
#練習問題5-7

sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12).reshape(3,4)

np.concatenate([sample_array1,sample_array2])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
#練習問題5-7

np.concatenate([sample_array1,sample_array2],axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [33]:
sample_list = [1,2,3,4,5]

np.array(sample_list) + 3

array([4, 5, 6, 7, 8])